# Aula 02

* Formatação de saída
* Definição de funções
* Criação de script em arquivo
* Vetores com `numpy`

### Formatação de saída

Definindo uma matriz 3x3 usando um `list`

In [1]:
matriz = [[(i*3) + j+1 for j in range(3)] for i in range(3)]
print(matriz)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


Imprimindo elementos de uma matriz (armazenada em um `list`) de acordo com uma formatação

In [2]:
for linha in matriz:
    saida = ""
    for celula in linha:
        saida += f"{celula}\t"
    
    print(saida)

1	2	3	
4	5	6	
7	8	9	


In [3]:
saida = []
for linha in matriz:
    saida.append("\t".join([f"{celula}" for celula in linha]))

print("\n".join(saida))

1	2	3
4	5	6
7	8	9


In [4]:
print("\n".join(["\t".join([f"{celula}" for celula in linha]) for linha in matriz]))

1	2	3
4	5	6
7	8	9


### Definição de funções

Definindo uma função para imprimir uma matriz

In [5]:
def print_matrix(matrix, sep_row="\n", sep_col="\t"):
    print(sep_row.join([sep_col.join([f"{cel}" for cel in row]) for row in matrix]))

Invocando a função para imprimir a matriz

In [6]:
print_matrix(matriz)

1	2	3
4	5	6
7	8	9


Definindo e chamando uma função para retornar a transposta de uma matriz:

In [7]:
def transpose(matrix):
    transpose = []
    for i, row in enumerate(matrix):
        for j, cel in enumerate(row):
            try: # if len(transpose) > j:
                row_t = transpose[j]
            except: # else:
                row_t = []
                transpose.append(row_t)
            row_t.append(cel)
    return transpose

matriz_t = transpose(matriz)
print_matrix(matriz_t)

1	4	7
2	5	8
3	6	9


### Criação de script em arquivo

Para criar um programa em python (script), basta criar um arquivo nomenado com a extensão `.py`, e o conteúdo deve ser com o código a ser executado pelo programa. Por exemplo, todas as linhas de código acima podem ser inseridas (na mesma ordem que estão dispostas) em um arquivo chamado `exemplo.py`. E para executar o script basta executar o comando `python exemplo.py`.

### Vetores com `numpy`

Importando a biblioteca `numpy`, e a apelidando de `np`

In [8]:
import numpy as np

Criando um vetor `numpy` a partir de um `list`

In [9]:
A = np.array([2.0, 3.0, 4.0])

Verificando o tipo

In [10]:
type(A)

numpy.ndarray

Imprimindo o vetor

In [11]:
print(A)

[2. 3. 4.]


Criando um vetor `numpy` a partir de uma matriz armazenada em um `list`

In [12]:
np_matriz = np.array(matriz)
print(np_matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Criando um vetor nulo de dimensão 2x10

In [13]:
np_mat = np.zeros((2, 10))
print(np_mat)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Atribuindo valores a posições de um vetor `numpy`

In [14]:
np_mat[:, 1] = 2
print(np_mat)

[[0. 2. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [15]:
np_mat[0, :] = -1
print(np_mat)

[[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [ 0.  2.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [16]:
np_mat[1, 6] = 43
print(np_mat)

[[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [ 0.  2.  0.  0.  0.  0. 43.  0.  0.  0.]]


Acessando valores a posições de um vetor `numpy`

In [17]:
np_mat[:, 6]

array([-1., 43.])

In [18]:
np_mat[:, :]

array([[-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [ 0.,  2.,  0.,  0.,  0.,  0., 43.,  0.,  0.,  0.]])

In [19]:
np_mat[0, :]

array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.])

In [20]:
np_mat[1, 9]

0.0

Recuprando o tamanho de cada um dos eixos ou dimensões de um vetor `numpy`. Esta meta-infomração de um vetor é conhecida como `shape`.

In [21]:
rows, columns = np.shape(np_mat)
print(f"{rows} linhas e {columns} colunas.")

2 linhas e 10 colunas.


In [22]:
eixos_mat = np.shape(np_mat)
print(eixos_mat)

(2, 10)


Atribuindo o quadrado do índice da coluna para cada posição na segunda linha.

In [23]:
for i in range(columns):
    np_mat[1, i] = i ** 2
print(np_mat)

[[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]]


Criando um vetor de dimensão 2x4 com valores aleatórios

In [24]:
np.random.random((2, 4))

array([[0.02394563, 0.23192398, 0.37779537, 0.92402576],
       [0.55915052, 0.75728346, 0.22173594, 0.42888024]])

## Atividade

Criar scripts python para cada aula: aula01.py e aula02.py. Os scripts devem conter os códigos correspondentes de cada aula, e devem ser executados com os comandos `python aula01.py` e `python aula02.py`, respectivamente. _Lembrete: a execução deve ser realizada com o ambiente virtual `ufrrj` ativado._

---

[Voltar para a página inicial](../README.md)