# Aula 03

* Operações em vetores/matrizes com `numpy`

### Operações em vetores/matrizes com `numpy`

Importanto as bibliotecas `numpy` e `scipy`

In [1]:
import numpy as np
import scipy

Matriz identidade de ordem 5

In [2]:
identidade = np.eye(5)
print(f"\nIdentidade:\n{identidade}")


Identidade:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Multiplicando duas matrizes

In [3]:
matriz_A = np.random.random((2, 4))
matriz_B = np.random.random((4, 1))
print(f"Matriz A {matriz_A.shape}:\n{matriz_A}")
print(f"\nMatriz B {matriz_B.shape}:\n{matriz_B}")

matriz_res = matriz_A.dot(matriz_B)
print(f"\nMatriz Resultante {matriz_res.shape}:\n{matriz_res}")

matriz_res = np.dot(matriz_A, matriz_B)
print(f"\nMatriz Resultante {matriz_res.shape}:\n{matriz_res}")

Matriz A (2, 4):
[[0.80622747 0.16293858 0.40953165 0.88793999]
 [0.55883883 0.88588852 0.42097691 0.30211766]]

Matriz B (4, 1):
[[0.82774696]
 [0.25950887]
 [0.54922851]
 [0.81734809]]

Matriz Resultante (2, 1):
[[1.66031885]
 [1.17062089]]

Matriz Resultante (2, 1):
[[1.66031885]
 [1.17062089]]


Definindo uma matriz 3x3

In [4]:
print(np.arange(9))
matriz = np.arange(9) - 4
matriz[4] = 1
matriz

[0 1 2 3 4 5 6 7 8]


array([-4, -3, -2, -1,  1,  1,  2,  3,  4])

Aplicando um `reshape` sobre o vetor para tomar a forma de uma matriz 3x3

In [5]:
matriz = matriz.reshape((3, 3))
matriz

array([[-4, -3, -2],
       [-1,  1,  1],
       [ 2,  3,  4]])

Posto (Rank) de uma matriz

In [6]:
np.linalg.matrix_rank(matriz)

3

Inversa de uma matriz

In [7]:
inversa = np.linalg.inv(matriz)
print(inversa)

[[-0.08333333 -0.5         0.08333333]
 [-0.5         1.         -0.5       ]
 [ 0.41666667 -0.5         0.58333333]]


Transposta de uma matriz

In [8]:
print(matriz.transpose())

[[-4 -1  2]
 [-3  1  3]
 [-2  1  4]]


Auto-valores e auto-vetores

In [9]:
auto_val, auto_vet = np.linalg.eig(matriz)
print(f"\nAuto-valores:\n{auto_val}")
print(f"\nAuto-vetores:\n{auto_vet}")


Auto-valores:
[-4.10169731  0.65843994  4.44325737]

Auto-vetores:
[[ 0.91743519  0.27538753 -0.33203716]
 [ 0.24177069 -0.79143133  0.35073528]
 [-0.31600569  0.54570886  0.87563468]]


Norma (de Frobenius) de uma matriz

In [10]:
np.linalg.norm(matriz)  # np.linalg.norm(matriz, ord='fro')

7.810249675906654

Norma (2-norm) de uma matriz

In [11]:
np.linalg.norm(matriz, ord=2)

7.372354605420665

Calculando a norma de uma matriz

In [12]:
vetor = matriz.flatten()
vetor

array([-4, -3, -2, -1,  1,  1,  2,  3,  4])

In [13]:
import math
resultado = 0
for valor in matriz.flatten():
    resultado += math.pow(valor, 2)

print(math.sqrt(resultado))

7.810249675906654


Distâncias entre vetores com `scipy` (euclidiana e manhatan)

In [14]:
vetor1 = np.random.random(5)
vetor2 = np.random.random(5)
print(vetor1)
print(vetor2)

from scipy.spatial import distance
dist_eucl = distance.euclidean(vetor1, vetor2)
dist_manh = distance.cityblock(vetor1, vetor2)
print(f"Euclidean: {dist_eucl}")
print(f"Manhatan: {dist_manh}")

[0.65351786 0.52802644 0.01348388 0.84851138 0.28806115]
[0.74803685 0.61023048 0.10571499 0.49745682 0.46519732]
Euclidean: 0.4228645785943754
Manhatan: 0.7971448738411324


Distância entre vetores com `numpý` (euclidiana normalizada)

In [15]:
diff_vetores = vetor1 - vetor2
print(diff_vetores)
print(np.linalg.norm(diff_vetores))

[-0.09451899 -0.08220404 -0.09223111  0.35105457 -0.17713617]
0.4228645785943754


Calculando a distância entre vetores

In [16]:
resultado = 0
for valor1, valor2 in zip(vetor1, vetor2):
    resultado += math.pow(valor1 - valor2, 2)

print(math.sqrt(resultado))

0.4228645785943754


Potência de uma matriz (`matriz^3`)

In [17]:
resultado = np.linalg.matrix_power(matriz, 3)
print(f"\nPotência:\n{resultado}")


Potência:
[[-69 -51 -39]
 [-13  13  25]
 [ 33  63  75]]


Determinante de uma matriz

In [18]:
det_mat = np.linalg.det(matriz)
print(f"Determinante: {det_mat}")

Determinante: -12.0


Número condição de uma matriz

In [19]:
np.linalg.cond(matriz)

11.298418902545862

Calculando o número condição de uma matriz

In [20]:
inversa = np.linalg.inv(matriz)
cond = np.linalg.norm(matriz) * np.linalg.norm(inversa)
print(f"Número condição: {cond}")

Número condição: 12.417505564502253


Decomposição LU

In [21]:
from scipy.linalg import lu
p, l, u = lu(matriz)
print(f"Matriz de permutação:\n{p}")
print(f"Triangular Inferior:\n{l}")
print(f"Triangular Superior:\n{u}")

Matriz de permutação:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Triangular Inferior:
[[ 1.          0.          0.        ]
 [ 0.25        1.          0.        ]
 [-0.5         0.85714286  1.        ]]
Triangular Superior:
[[-4.         -3.         -2.        ]
 [ 0.          1.75        1.5       ]
 [ 0.          0.          1.71428571]]


Decomposição QR

In [22]:
q, r = scipy.linalg.qr(matriz)
print(f"\nMatriz Q:\n{q}")
print(f"\nMatriz R:\n{r}")


Matriz Q:
[[-0.87287156 -0.1040313   0.47673129]
 [-0.21821789 -0.79063786 -0.57207755]
 [ 0.43643578 -0.60338152  0.66742381]]

Matriz R:
[[ 4.58257569  3.70970413  3.27326835]
 [ 0.         -2.28868854 -2.99610136]
 [ 0.          0.          1.14415511]]


Verificando se duas matrizes podem ser consideradas iguais (valores correspondentes suficientemente próximos dado uma margem de erro de precisão)

In [23]:
scipy.allclose(matriz, np.dot(q, r), atol=1e-32)

True

---

[Voltar para a página inicial](../README.md)